<?php
set_time_limit(0);
defined('BASEPATH') OR exit('No direct script access allowed');

class Send extends APIMaster {

	public function index()
    {
        $emails = array(           

          
        

            // 'harbhyodun@gmail.com',
            // 'harbhyodun@gmail.com',
            // 'sukhveer251002@gmail.com',
            // 'chukspaul.cp@gmail.com',
            // 'johnhicks3674@att.net',
            // 'blagovest8410@gmail.com',
            // 'blagovest8410@gmail.com',
            // 'nathanielgorroh5@gmail.com',
            // 'ashahzaib366@icloud.com',
            // 'izman584@yahoo.com',
            // 'anazorkosi@gmail.com',
            // 'a.sonu786@gmail.com',
            // 'kelvinsarfo17@gmail.com',
            // 'aromeabikiaje@gmail.com',
            // 'aromeabikiaje@gmail.com',
            // 'delmarbennett@revoroof.com',
            // 'talhaismail20@gmail.com',
            // 'profx48@gmail.com',
            // 'mr.tradzuma@gmail.com',
            // 'mr.tradzuma@gmail.com',
            // 'mr.tradzuma@gmail.com',
            // 'dg_building@yahoo.com',
            // 'aromeabikiaje@gmail.com',
            // 'fosuaforson@gmail.com',
            // 'Alexanderbmet@outlook.com',
            // 'jb_mistry@hotmail.com',
            // 'Alexanderbmet@outlook.com',
            // 'saidmuhumed98@gmail.com',
            // 'harnoric@gmail.com',
            // 'ashwinshaumia@gmail.com',
            // 'ashwinshaumia@gmail.com',
            // 'ashwinshaumia@gmail.com',
            // 'ashwinshaumia@gmail.com',
            // 'aromeabikiaje@gmail.com',
            // 'abdisalandahir12@gmail.com',
            // 'mr.tradzuma@gmail.com',
            // 'abdisalandahirahmed@gmail.com',
            // 'mr.tradzuma@gmail.com',
            // 'mr.tradzuma@gmail.com',
            // 'kayodeab@outlook.com',
            // 'ith4941@naver.com',
            // 'ashwinshaumia@gmail.com',
            // 'ashwinshaumia@gmail.com',
            // 'yadavpraveen898@gmail.com',
            // 'alichukwudaniel@gmail.com',
            // 'jcwc69@gmail.com',
            // 'seektruth144@gmail.com',
            // 'rapheal205@YAHOO.COM',
            // 'adekunlegolden3@gmail.com',
            // 'danial.da95@gmail.com',
            // 'nathiraaden@gmail.com',
            // 'slyb20087@gmail.com',
            // 'mona.sj.alhosani@hotmail.com',
            // 'fernandoarevalo1097@gmail.com',
            // 'ozzoude.matt@yahoo.com',
            // 'simmyb2917@gmail.com',
            // 'Olaf.klein74@googlemail.com',
            // 'fdavibarbosa@gmail.com',
            // 'jobsani2424@gmail.com',
            // 'simor200@gmail.com',
            // 'guenther.h2016@outlook.de',
            // 'jonasokani@yahoo.com',
            // 'bernardbarka@gmail.com',
            // 'mteiwilfredmuya11@gmail.com',
            // 'mteiwilfredmuya11@gmail.com',
            // 'mkraminer@gmail.com',
            // 'tandy.vangtan@gmail.com',
            // 'xarielwalterx@gmail.com',
            // 'cfc.jcorrigan@gmail.com',
            // 'Harveyluke.383@gmail.com',
            // 'davidnnaji01@gmail.com',
            // 'elisefu99@gmail.com',
            // 'nurun@protonmail.com',
            // 'john.dise.mason@gmail.com',
            // 'abodealommiry@gmail.com',
            // 'abodealommiry@gmail.com',
            // 'abodealommiry@gmail.com',
            // 'talktoebere@gmail.com',
            // 'quantumspace100@protonmail.com',
            // 'talktoebere@gmail.com',
            // 'njienggaston@gmail.com',
            // 'njienggaston@gmail.com',
            // 'ayadinunochimnondu21@gmail.com',
            // 'ronanchit@gmail.com',
            // 'ronanchit@gmail.com',
            // 'cjweave4@gmail.com',
            // 'cjweave4@gmail.com',
            // 'nsubukah@gmail.com',
            // 'joshuamadighi14@gmail.com',
            // 'swanzy77u@gmail.com',
            // 'henry.anyanele@gmail.com',
            // 'victortimilehin02@gmail.com',
            // 'victortimilehin02@gmail.com',
            // 'jcwc69@gmail.com',
            // 'bmofinancialltd@gmail.com',
            // 'joshuamadighi14@gmail.com',
            // 'rafickquaye@gmail.com',
            // 'julianorck@gmail.com',
            // 'ayuop154@gmail.com',
            // 'thompsongeorge19k@gmail.com',
            // 'moseseke0810@gmail.com',
            // 'mustysani@gmail.com',
            // 'moseseke0810@gmail.com',
            // 'festusadegoke2001@gmail.com',
            // 'popoolaoluwafemi2015@gmail.com',
            // 'festusadegoke2001@gmail.com',
            // 'fosuaforson@gmail.com',
            // 'bachirmuhamad@gmail.com',
            // 'mwangierick007@gmail.com',
            // 'abbassalihuusman1505@gmail.com',
            // 'shilohchinakwe@gmail.com',
            // 'berangermededji@hotmail.com',
            // 'okwomaelvis@gmail.com',
            // 'michaelgbolahan360@gmail.com',
            // 'sediq.mangal13@yahoo.com',
            // 'njienggaston@gmail.com',
            // 'abbasali.tk@gmail.com',
            // 'olajubuolalekan@gmail.com',
            // 'mwangierick007@gmail.com',
            // 'etuk.iniabasi@gmail.com',
            // 'izman584@yahoo.com',
            // 'izman584@yahoo.com',
            // 'santiagomefr@gmail.com',
            // 'saif.elfarhani@gmail.com',
            // 'hassan395251@gmail.com',
            // 'hassan395251@gmail.com',
            // 'profx48@gmail.com',
            // 'kulkb46@gmail.com',
            // 'cjweave4@gmail.com',
            // 'ashahzaib366@icloud.com',
            // 'm.ali.nour2013@gmail.com',
            // 'ebuka4power247@gmail.com',
            // 'rotimiojo247@gmail.com',
            // 'suavereal@gmail.com',
            // 'ith4941@naver.com',
            // 'izman584@yahoo.com',
            // 'etuk.iniabasi@gmail.com',
            // 'etuk.iniabasi@gmail.com',
            // 'palleramulu@gmail.com',

            
            // 'ankanghosh010@gmail.com',
            // 'gigabytelite.001@gmail.com',
            // 'andrefx930@gmail.com',
            // 'maximus.trade.management@gmail.com',
            // 'fayprince02@gmail.com',
            // 'apipk58@gmail.com',
            // 'czvekan@gmail.com',
            // 'ecomgigant@gmail.com',
            // 'Matozsolti@gmail.com',
            // 'abdiazizs853@gmail.com',
            // 'abdiazizs853@gmail.com',
            // 'contact@jamrockcapitol.com',
            // 'check4sunshine@gmail.com',
            // 'vitorrrodrigues1996@gmail.com',
            // 'donterreon@hotmail.com',
            // 'mona.sj.alhosani@hotmail.com',
            // 'abdullohfozilov55@gmail.com',
            // 'yabayomi6@gmail.com',
            // 'yabayomi6@gmail.com',
            // 'vsev12@gmail.com',
            // 'festusadegoke2001@gmail.com',
            // freddyaguirre05@yahoo.com
            // 'quarshiep59@gmail.com',
            // 'festusadegoke2001@gmail.com',
            // 'skgmalinga@gmail.com',
            // 'skgmalinga@gmail.com',
            // 'skgmalinga@gmail.com',
            // 'kayodek505@gmail.com',
            // 'kayodek505@gmail.com',
            // 'johnhicks3674@att.net',
            // 'abdiazizs853@gmail.com',
            // 'investmentnadeau@gmail.com',
            // 'abdiazizs853@gmail.com',
            // 'abdiazizs853@gmail.com',
            // 'samueladeoti77@gmail.com',
            // 'johnhicks3674@att.net',
            // 'adanmohamoud1@gmail.com',
            // 'vsev12@gmail.com',
            // 'Ronaldo_martins7@hotmail.com',
            // 'johnhicks3674@att.net',
            // 'eb.dramm@gmail.com',
            // 'inosakhare005@gmail.com',
            // 'ubaisaiah405@gmail.com',
            // 'ubaisaiah405@gmail.com',
            // 'profx48@gmail.com',
            // 'profx48@gmail.com',
            // 'ilyasabdullahihashi@gmail.com',
            // 'cjweave4@gmail.com',
            // 'oluclinton4@gmail.com',
            // felix.aigbogun@yahoo.com
            // 'thejus@gmail.com',
            // 'slyb20087@gmail.com',
            // oyelakin.omotayo83@yahoo.com
            // 'profx48@gmail.com',
            // 'benjaminsuboni@gmail.com',
            // ojeanba123@outlook.com
            // 'olubiyitimilehin87@gmail.com',
            // 'fxking557@gmail.com',
            // 'vaclavbee@gmail.com',
            // 'marcelrump@protonmail.com',
            // 'sywin.mooc@hotmail.co.uk',
            // 'chidera110011@gmail.com',
            // 'fostermay7@gmail.com',
            // 'hamzeezy66@gmail.com',
            // 'hamzeezy66@gmail.com',
            // 'aromeabikiaje@gmail.com',
            // 'seektruth144@gmail.com',
            // 'ernestekuje@gmail.com',
            // 'hamzeezy66@gmail.com',
            // diran_adegoke@yahoo.com
            // 'ogwucheemma53@gmail.com',
            // 'deepakjhanwar.dj@gmail.com',
            // 'bookseller608@gmail.com',
            // 'richardtaylor8377998@gmail.com',
            // 'damilolakenny23@gmail.com',
            // 'michaelgbolahan360@gmail.com',
            // 'davsondavidjob@gmail.com',
            // 'Bamidelesalawe@gmail.com',
            

            // "ankanghosh010@gmail.com",
            // "gigabytelite.001@gmail.com"
           
        );
        $users = array_unique($emails);

        foreach ($users as $key => $value) {
            $this->load->helper('email_helper');
            $this->load->library('mailer');  
            $body = file_get_contents(base_url('assets/mail/launch.html'));

            
            $email = send_email($value, 'We are now live - 20% Discount', $body,'','',9);
            echo "send ".$key."  ".$value."<br/>";
        }

    }

}
